### ISSUE TITLE
Does this library generate RFC 6902 patches?

### ISSUE THREAD

**Issue by safwank** [talentdeficit/json#2]
If not, do you know of any Erlang/Elixir library that does? Apologies if this isn't the right forum.

**Comment by talentdeficit** [comment]
the rfc 6902 functionality of `json` is limited to applying patches to erlang terms that represent json. so for example if you have a map like `Map = %{ <<"id">> => 1, <<"value">> => true }` and you have a patch like `Patch = #{<<"op">> => <<"replace">>, <<"path">> => <<"/value">>, <<"value">> => false }` you can call `json:patch([Patch], Map)` and get `%{ <<"id">> => 1, <<"value">> => false }`

i'd be open to adding code to generate patches though. i don't know of any library that currently does that

**Comment by safwank** [comment]
Thanks for getting back to me. I've decided to roll my own implementation of the RFC instead, albeit partially.
